// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineAuctionSystem.Persistence;

#nullable disable

namespace OnlineAuctionSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231013193950_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineAuctionSystem.Persistence.Entities.AuctionDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<double>("StartingPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("AuctionDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Description for Auction 1",
                            EndTime = new DateTime(2023, 10, 14, 21, 39, 49, 820, DateTimeKind.Local).AddTicks(8654),
                            Name = "Auction 1",
                            SellerId = -1,
                            StartingPrice = 100.0
                        },
                        new
                        {
                            Id = -2,
                            Description = "Description for Auction 2",
                            EndTime = new DateTime(2023, 10, 15, 21, 39, 49, 820, DateTimeKind.Local).AddTicks(8741),
                            Name = "Auction 2",
                            SellerId = -2,
                            StartingPrice = 50.0
                        });
                });

            modelBuilder.Entity("OnlineAuctionSystem.Persistence.Entities.BidDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<double>("BidAmount")
                        .HasColumnType("float");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("BidDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuctionId = -1,
                            BidAmount = 120.0,
                            BidderId = -2
                        },
                        new
                        {
                            Id = -2,
                            AuctionId = -2,
                            BidAmount = 60.0,
                            BidderId = -1
                        });
                });

            modelBuilder.Entity("OnlineAuctionSystem.Persistence.Entities.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("UserDbs");

                    b.HasData(
                        new
                        {
                            Id = -1
                        },
                        new
                        {
                            Id = -2
                        });
                });

            modelBuilder.Entity("OnlineAuctionSystem.Persistence.Entities.AuctionDb", b =>
                {
                    b.HasOne("OnlineAuctionSystem.Persistence.Entities.UserDb", "SellerDb")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerDb");
                });

            modelBuilder.Entity("OnlineAuctionSystem.Persistence.Entities.BidDb", b =>
                {
                    b.HasOne("OnlineAuctionSystem.Persistence.Entities.AuctionDb", "AuctionDb")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineAuctionSystem.Persistence.Entities.UserDb", "BidderDb")
                        .WithMany()
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AuctionDb");

                    b.Navigation("BidderDb");
                });
#pragma warning restore 612, 618
        }
    }
}
